### PR TITLE
Fix CAPEC-USAGE.md code filter example

### PR DESCRIPTION
**Pull request by praetorian-anthony-weems**

### CODE REVIEW

**Comment by jburns12** [comment]
Thanks for catching this and making the PR @praetorian-anthony-weems!

**Comment by praetorian-anthony-weems** [comment]
Sure thing @jburns12! As an aside, I've been digging into the project and was curious if there's a discussion forum or Slack channel I could join to ask questions and chat.

**Comment by jburns12** [comment]
Hey @praetorian-anthony-weems - send us an email at attack@mitre.org, and we'll be happy to follow up!

**Comment by rpiazza** [comment]
@praetorian-anthony-weems - any questions specific to CAPEC can be sent to capec@mitre.org :-)

**Pull request merged**
